### ISSUE TITLE
pagecloner not functional cloning mpform forms

### ISSUE THREAD

**Issue by winkelmannlars** [aldus/pagecloner#1]
I have Lepton 2.2.1 and MPForms 1.1.12 on a Strato Account. Today I recognized that the page shows neither the usual Thankyou text or, if choosen the success page after submitting the form. But the form is send and receives correctly. When the error occurs, droplets are not parsed and shown as [[dropletname]] in the page. The following message is shown when I switch on the php error messenger:

```
Fatal error:
Uncaught exception 'PDOException' with message 'SQLSTATE[42S22]:
Column not found:
1054 Unknown column 'field27' in 'field list'' in ...../framework/class.database.php:649
```

I recognized that PageCloner lacks to create a new result-table in the database for a cloned mpform neither resets the linked section in MPform options. I think this should be solved because you otherwise have to manually change the section link in the options and to manually create a new results SQL table for the cloned form with the right new fieldnames. If you leave it as it works, you get inconsistent Data an error like described above.

**Comment by labby** [comment]
fixed on 2016-09-20
